services:
  firstdue-listener:
    image: kickedsoda/firstdue-listener:latest
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - nginx-net
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  nginx-net:
    driver: bridge