services:
  firstdue-listener:
    image: kickedsoda/firstdue-listener:latest
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - nginx-net
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${PORT}/health"]
      timeout: 5s
      interval: 30s
      retries: 3
      start_period: 40s

networks:
  nginx-net:
    external: true